import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";
import { TRPCReactProvider } from "@/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import PageContent from "./_components/layout/page-content";
import Sidebar from "./_components/layout/sidebar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased", inter.variable)}>
        <ClerkProvider>
          <TRPCReactProvider>
            <div className="flex flex-col md:flex-row">
              <Sidebar />
              <PageContent>
                {children}
              </PageContent>
            </div>
          </TRPCReactProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
